// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const getAPIKeyByID = `-- name: GetAPIKeyByID :one
SELECT id, name, key_prefix, key_hash, status, created_at, last_used_at, revoked_at FROM api_keys WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAPIKeyByID(ctx context.Context, id uuid.UUID) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByID, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.Status,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAPIKeyByPrefix = `-- name: GetAPIKeyByPrefix :one
SELECT id, name, key_prefix, key_hash, status, created_at, last_used_at, revoked_at FROM api_keys WHERE key_prefix = $1 LIMIT 1
`

func (q *Queries) GetAPIKeyByPrefix(ctx context.Context, keyPrefix string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByPrefix, keyPrefix)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.Status,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const insertAPIKey = `-- name: InsertAPIKey :one
INSERT INTO api_keys (name, key_prefix, key_hash, status)
VALUES ($1, $2, $3, 'active')
RETURNING id, name, key_prefix, key_hash, status, created_at, last_used_at, revoked_at
`

type InsertAPIKeyParams struct {
	Name      string `json:"name"`
	KeyPrefix string `json:"key_prefix"`
	KeyHash   string `json:"key_hash"`
}

func (q *Queries) InsertAPIKey(ctx context.Context, arg InsertAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, insertAPIKey, arg.Name, arg.KeyPrefix, arg.KeyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.Status,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, name, key_prefix, key_hash, status, created_at, last_used_at, revoked_at FROM api_keys
WHERE ($1::text IS NULL OR status = $1)
ORDER BY created_at DESC
`

func (q *Queries) ListAPIKeys(ctx context.Context, dollar_1 string) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeys, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.KeyPrefix,
			&i.KeyHash,
			&i.Status,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAPIKeyRotating = `-- name: MarkAPIKeyRotating :exec
UPDATE api_keys SET status = 'rotating' WHERE id = $1 AND status = 'active'
`

func (q *Queries) MarkAPIKeyRotating(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAPIKeyRotating, id)
	return err
}

const revokeAPIKey = `-- name: RevokeAPIKey :exec
UPDATE api_keys SET status = 'revoked', revoked_at = now() WHERE id = $1
`

func (q *Queries) RevokeAPIKey(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAPIKey, id)
	return err
}

const touchAPIKeyLastUsed = `-- name: TouchAPIKeyLastUsed :exec
UPDATE api_keys SET last_used_at = now() WHERE id = $1
`

func (q *Queries) TouchAPIKeyLastUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchAPIKeyLastUsed, id)
	return err
}
