// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: artifacts.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const getArtifactByID = `-- name: GetArtifactByID :one
SELECT id, test_case_id, kind, content_type, object_key, size_bytes, sha256, created_at FROM artifacts WHERE id = $1 LIMIT 1
`

func (q *Queries) GetArtifactByID(ctx context.Context, id uuid.UUID) (Artifact, error) {
	row := q.db.QueryRow(ctx, getArtifactByID, id)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.TestCaseID,
		&i.Kind,
		&i.ContentType,
		&i.ObjectKey,
		&i.SizeBytes,
		&i.Sha256,
		&i.CreatedAt,
	)
	return i, err
}

const insertArtifact = `-- name: InsertArtifact :one
INSERT INTO artifacts (test_case_id, kind, content_type, object_key, size_bytes, sha256)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, test_case_id, kind, content_type, object_key, size_bytes, sha256, created_at
`

type InsertArtifactParams struct {
	TestCaseID  uuid.UUID `json:"test_case_id"`
	Kind        string    `json:"kind"`
	ContentType string    `json:"content_type"`
	ObjectKey   string    `json:"object_key"`
	SizeBytes   int64     `json:"size_bytes"`
	Sha256      string    `json:"sha256"`
}

func (q *Queries) InsertArtifact(ctx context.Context, arg InsertArtifactParams) (Artifact, error) {
	row := q.db.QueryRow(ctx, insertArtifact,
		arg.TestCaseID,
		arg.Kind,
		arg.ContentType,
		arg.ObjectKey,
		arg.SizeBytes,
		arg.Sha256,
	)
	var i Artifact
	err := row.Scan(
		&i.ID,
		&i.TestCaseID,
		&i.Kind,
		&i.ContentType,
		&i.ObjectKey,
		&i.SizeBytes,
		&i.Sha256,
		&i.CreatedAt,
	)
	return i, err
}

const listArtifactsByCase = `-- name: ListArtifactsByCase :many
SELECT id, test_case_id, kind, content_type, object_key, size_bytes, sha256, created_at FROM artifacts WHERE test_case_id = $1 ORDER BY created_at
`

func (q *Queries) ListArtifactsByCase(ctx context.Context, testCaseID uuid.UUID) ([]Artifact, error) {
	rows, err := q.db.Query(ctx, listArtifactsByCase, testCaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Artifact{}
	for rows.Next() {
		var i Artifact
		if err := rows.Scan(
			&i.ID,
			&i.TestCaseID,
			&i.Kind,
			&i.ContentType,
			&i.ObjectKey,
			&i.SizeBytes,
			&i.Sha256,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
