// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: github_oidc_policies.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const deleteOIDCPolicy = `-- name: DeleteOIDCPolicy :exec
DELETE FROM github_oidc_policies WHERE id = $1
`

func (q *Queries) DeleteOIDCPolicy(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteOIDCPolicy, id)
	return err
}

const getOIDCPolicyByID = `-- name: GetOIDCPolicyByID :one
SELECT id, name, enabled, priority, match_repository, match_repository_owner, match_workflow, match_ref, match_environment, grant_role, created_at, updated_at FROM github_oidc_policies WHERE id = $1 LIMIT 1
`

func (q *Queries) GetOIDCPolicyByID(ctx context.Context, id uuid.UUID) (GithubOidcPolicy, error) {
	row := q.db.QueryRow(ctx, getOIDCPolicyByID, id)
	var i GithubOidcPolicy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Enabled,
		&i.Priority,
		&i.MatchRepository,
		&i.MatchRepositoryOwner,
		&i.MatchWorkflow,
		&i.MatchRef,
		&i.MatchEnvironment,
		&i.GrantRole,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertOIDCPolicy = `-- name: InsertOIDCPolicy :one
INSERT INTO github_oidc_policies (
    name, enabled, priority,
    match_repository, match_repository_owner, match_workflow, match_ref, match_environment,
    grant_role
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, name, enabled, priority, match_repository, match_repository_owner, match_workflow, match_ref, match_environment, grant_role, created_at, updated_at
`

type InsertOIDCPolicyParams struct {
	Name                 string  `json:"name"`
	Enabled              bool    `json:"enabled"`
	Priority             int32   `json:"priority"`
	MatchRepository      *string `json:"match_repository"`
	MatchRepositoryOwner *string `json:"match_repository_owner"`
	MatchWorkflow        *string `json:"match_workflow"`
	MatchRef             *string `json:"match_ref"`
	MatchEnvironment     *string `json:"match_environment"`
	GrantRole            string  `json:"grant_role"`
}

func (q *Queries) InsertOIDCPolicy(ctx context.Context, arg InsertOIDCPolicyParams) (GithubOidcPolicy, error) {
	row := q.db.QueryRow(ctx, insertOIDCPolicy,
		arg.Name,
		arg.Enabled,
		arg.Priority,
		arg.MatchRepository,
		arg.MatchRepositoryOwner,
		arg.MatchWorkflow,
		arg.MatchRef,
		arg.MatchEnvironment,
		arg.GrantRole,
	)
	var i GithubOidcPolicy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Enabled,
		&i.Priority,
		&i.MatchRepository,
		&i.MatchRepositoryOwner,
		&i.MatchWorkflow,
		&i.MatchRef,
		&i.MatchEnvironment,
		&i.GrantRole,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listEnabledOIDCPolicies = `-- name: ListEnabledOIDCPolicies :many
SELECT id, name, enabled, priority, match_repository, match_repository_owner, match_workflow, match_ref, match_environment, grant_role, created_at, updated_at FROM github_oidc_policies WHERE enabled = true ORDER BY priority ASC
`

func (q *Queries) ListEnabledOIDCPolicies(ctx context.Context) ([]GithubOidcPolicy, error) {
	rows, err := q.db.Query(ctx, listEnabledOIDCPolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GithubOidcPolicy{}
	for rows.Next() {
		var i GithubOidcPolicy
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Enabled,
			&i.Priority,
			&i.MatchRepository,
			&i.MatchRepositoryOwner,
			&i.MatchWorkflow,
			&i.MatchRef,
			&i.MatchEnvironment,
			&i.GrantRole,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOIDCPolicies = `-- name: ListOIDCPolicies :many
SELECT id, name, enabled, priority, match_repository, match_repository_owner, match_workflow, match_ref, match_environment, grant_role, created_at, updated_at FROM github_oidc_policies ORDER BY priority ASC
`

func (q *Queries) ListOIDCPolicies(ctx context.Context) ([]GithubOidcPolicy, error) {
	rows, err := q.db.Query(ctx, listOIDCPolicies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GithubOidcPolicy{}
	for rows.Next() {
		var i GithubOidcPolicy
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Enabled,
			&i.Priority,
			&i.MatchRepository,
			&i.MatchRepositoryOwner,
			&i.MatchWorkflow,
			&i.MatchRef,
			&i.MatchEnvironment,
			&i.GrantRole,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateOIDCPolicy = `-- name: UpdateOIDCPolicy :one
UPDATE github_oidc_policies
SET name = $2, enabled = $3, priority = $4,
    match_repository = $5, match_repository_owner = $6,
    match_workflow = $7, match_ref = $8, match_environment = $9,
    grant_role = $10, updated_at = now()
WHERE id = $1
RETURNING id, name, enabled, priority, match_repository, match_repository_owner, match_workflow, match_ref, match_environment, grant_role, created_at, updated_at
`

type UpdateOIDCPolicyParams struct {
	ID                   uuid.UUID `json:"id"`
	Name                 string    `json:"name"`
	Enabled              bool      `json:"enabled"`
	Priority             int32     `json:"priority"`
	MatchRepository      *string   `json:"match_repository"`
	MatchRepositoryOwner *string   `json:"match_repository_owner"`
	MatchWorkflow        *string   `json:"match_workflow"`
	MatchRef             *string   `json:"match_ref"`
	MatchEnvironment     *string   `json:"match_environment"`
	GrantRole            string    `json:"grant_role"`
}

func (q *Queries) UpdateOIDCPolicy(ctx context.Context, arg UpdateOIDCPolicyParams) (GithubOidcPolicy, error) {
	row := q.db.QueryRow(ctx, updateOIDCPolicy,
		arg.ID,
		arg.Name,
		arg.Enabled,
		arg.Priority,
		arg.MatchRepository,
		arg.MatchRepositoryOwner,
		arg.MatchWorkflow,
		arg.MatchRef,
		arg.MatchEnvironment,
		arg.GrantRole,
	)
	var i GithubOidcPolicy
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Enabled,
		&i.Priority,
		&i.MatchRepository,
		&i.MatchRepositoryOwner,
		&i.MatchWorkflow,
		&i.MatchRef,
		&i.MatchEnvironment,
		&i.GrantRole,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
