// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"encoding/json"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

type ApiKey struct {
	ID         uuid.UUID   `json:"id"`
	Name       string      `json:"name"`
	KeyPrefix  string      `json:"key_prefix"`
	KeyHash    string      `json:"key_hash"`
	Status     string      `json:"status"`
	CreatedAt  time.Time   `json:"created_at"`
	LastUsedAt **time.Time `json:"last_used_at"`
	RevokedAt  **time.Time `json:"revoked_at"`
}

type Artifact struct {
	ID          uuid.UUID `json:"id"`
	TestCaseID  uuid.UUID `json:"test_case_id"`
	Kind        string    `json:"kind"`
	ContentType string    `json:"content_type"`
	ObjectKey   string    `json:"object_key"`
	SizeBytes   int64     `json:"size_bytes"`
	Sha256      string    `json:"sha256"`
	CreatedAt   time.Time `json:"created_at"`
}

type GithubOidcPolicy struct {
	ID                   uuid.UUID `json:"id"`
	Name                 string    `json:"name"`
	Enabled              bool      `json:"enabled"`
	Priority             int32     `json:"priority"`
	MatchRepository      *string   `json:"match_repository"`
	MatchRepositoryOwner *string   `json:"match_repository_owner"`
	MatchWorkflow        *string   `json:"match_workflow"`
	MatchRef             *string   `json:"match_ref"`
	MatchEnvironment     *string   `json:"match_environment"`
	GrantRole            string    `json:"grant_role"`
	CreatedAt            time.Time `json:"created_at"`
	UpdatedAt            time.Time `json:"updated_at"`
}

type OidcClaim struct {
	ID              uuid.UUID       `json:"id"`
	ReportID        uuid.NullUUID   `json:"report_id"`
	Issuer          string          `json:"issuer"`
	Subject         string          `json:"subject"`
	Audience        string          `json:"audience"`
	Repository      *string         `json:"repository"`
	RepositoryOwner *string         `json:"repository_owner"`
	Workflow        *string         `json:"workflow"`
	Ref             *string         `json:"ref"`
	Environment     *string         `json:"environment"`
	RawClaims       json.RawMessage `json:"raw_claims"`
	VerifiedAt      time.Time       `json:"verified_at"`
}

type RefreshToken struct {
	ID         uuid.UUID     `json:"id"`
	SessionID  uuid.UUID     `json:"session_id"`
	TokenHash  string        `json:"token_hash"`
	IssuedAt   time.Time     `json:"issued_at"`
	ExpiresAt  time.Time     `json:"expires_at"`
	UsedAt     **time.Time   `json:"used_at"`
	ReplacedBy uuid.NullUUID `json:"replaced_by"`
}

type Report struct {
	ID                    uuid.UUID     `json:"id"`
	ReportGroupID         uuid.UUID     `json:"report_group_id"`
	Source                string        `json:"source"`
	CommitSha             *string       `json:"commit_sha"`
	Branch                *string       `json:"branch"`
	Status                string        `json:"status"`
	IngestError           *string       `json:"ingest_error"`
	TotalSuites           int32         `json:"total_suites"`
	TotalCases            int32         `json:"total_cases"`
	PassedCases           int32         `json:"passed_cases"`
	FailedCases           int32         `json:"failed_cases"`
	SkippedCases          int32         `json:"skipped_cases"`
	FlakyCases            int32         `json:"flaky_cases"`
	DurationMs            *int64        `json:"duration_ms"`
	UploadedByApiKeyID    uuid.NullUUID `json:"uploaded_by_api_key_id"`
	UploadedByOidcSubject *string       `json:"uploaded_by_oidc_subject"`
	IdempotencyKey        *string       `json:"idempotency_key"`
	CreatedAt             time.Time     `json:"created_at"`
	IngestedAt            **time.Time   `json:"ingested_at"`
}

type ReportGroup struct {
	ID          uuid.UUID `json:"id"`
	Slug        string    `json:"slug"`
	DisplayName string    `json:"display_name"`
	Description *string   `json:"description"`
	CreatedAt   time.Time `json:"created_at"`
}

type ReportJsonFile struct {
	ID        uuid.UUID `json:"id"`
	ReportID  uuid.UUID `json:"report_id"`
	ObjectKey string    `json:"object_key"`
	SizeBytes int64     `json:"size_bytes"`
	Sha256    string    `json:"sha256"`
	CreatedAt time.Time `json:"created_at"`
}

type ReportsIdempotency struct {
	IdempotencyKey string    `json:"idempotency_key"`
	ReportID       uuid.UUID `json:"report_id"`
	ClaimedAt      time.Time `json:"claimed_at"`
}

type Session struct {
	ID         uuid.UUID   `json:"id"`
	TokenHash  string      `json:"token_hash"`
	UserID     uuid.UUID   `json:"user_id"`
	IssuedAt   time.Time   `json:"issued_at"`
	ExpiresAt  time.Time   `json:"expires_at"`
	LastSeenAt time.Time   `json:"last_seen_at"`
	Ip         *netip.Addr `json:"ip"`
	UserAgent  *string     `json:"user_agent"`
	RevokedAt  **time.Time `json:"revoked_at"`
}

type Suite struct {
	ID            uuid.UUID     `json:"id"`
	ReportID      uuid.UUID     `json:"report_id"`
	ParentSuiteID uuid.NullUUID `json:"parent_suite_id"`
	Title         string        `json:"title"`
	File          string        `json:"file"`
	Line          *int32        `json:"line"`
	Col           *int32        `json:"col"`
	DurationMs    *int64        `json:"duration_ms"`
	Ordinal       int32         `json:"ordinal"`
}

type TestCase struct {
	ID           uuid.UUID       `json:"id"`
	SuiteID      uuid.UUID       `json:"suite_id"`
	Title        string          `json:"title"`
	Status       string          `json:"status"`
	RetryCount   int32           `json:"retry_count"`
	DurationMs   *int64          `json:"duration_ms"`
	ErrorMessage *string         `json:"error_message"`
	ErrorStack   *string         `json:"error_stack"`
	Annotations  json.RawMessage `json:"annotations"`
	Ordinal      int32           `json:"ordinal"`
}

type User struct {
	ID          uuid.UUID   `json:"id"`
	GithubID    int64       `json:"github_id"`
	GithubLogin string      `json:"github_login"`
	Email       *string     `json:"email"`
	DisplayName *string     `json:"display_name"`
	AvatarUrl   *string     `json:"avatar_url"`
	Role        string      `json:"role"`
	CreatedAt   time.Time   `json:"created_at"`
	LastLoginAt **time.Time `json:"last_login_at"`
}
