// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oidc_claims.sql

package sqlcgen

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const insertOIDCClaims = `-- name: InsertOIDCClaims :one
INSERT INTO oidc_claims (
    report_id, issuer, subject, audience,
    repository, repository_owner, workflow, ref, environment, raw_claims
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, report_id, issuer, subject, audience, repository, repository_owner, workflow, ref, environment, raw_claims, verified_at
`

type InsertOIDCClaimsParams struct {
	ReportID        uuid.NullUUID   `json:"report_id"`
	Issuer          string          `json:"issuer"`
	Subject         string          `json:"subject"`
	Audience        string          `json:"audience"`
	Repository      *string         `json:"repository"`
	RepositoryOwner *string         `json:"repository_owner"`
	Workflow        *string         `json:"workflow"`
	Ref             *string         `json:"ref"`
	Environment     *string         `json:"environment"`
	RawClaims       json.RawMessage `json:"raw_claims"`
}

func (q *Queries) InsertOIDCClaims(ctx context.Context, arg InsertOIDCClaimsParams) (OidcClaim, error) {
	row := q.db.QueryRow(ctx, insertOIDCClaims,
		arg.ReportID,
		arg.Issuer,
		arg.Subject,
		arg.Audience,
		arg.Repository,
		arg.RepositoryOwner,
		arg.Workflow,
		arg.Ref,
		arg.Environment,
		arg.RawClaims,
	)
	var i OidcClaim
	err := row.Scan(
		&i.ID,
		&i.ReportID,
		&i.Issuer,
		&i.Subject,
		&i.Audience,
		&i.Repository,
		&i.RepositoryOwner,
		&i.Workflow,
		&i.Ref,
		&i.Environment,
		&i.RawClaims,
		&i.VerifiedAt,
	)
	return i, err
}

const listOIDCClaimsBySubject = `-- name: ListOIDCClaimsBySubject :many
SELECT id, report_id, issuer, subject, audience, repository, repository_owner, workflow, ref, environment, raw_claims, verified_at FROM oidc_claims WHERE subject = $1 ORDER BY verified_at DESC LIMIT $2
`

type ListOIDCClaimsBySubjectParams struct {
	Subject string `json:"subject"`
	Limit   int32  `json:"limit"`
}

func (q *Queries) ListOIDCClaimsBySubject(ctx context.Context, arg ListOIDCClaimsBySubjectParams) ([]OidcClaim, error) {
	rows, err := q.db.Query(ctx, listOIDCClaimsBySubject, arg.Subject, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OidcClaim{}
	for rows.Next() {
		var i OidcClaim
		if err := rows.Scan(
			&i.ID,
			&i.ReportID,
			&i.Issuer,
			&i.Subject,
			&i.Audience,
			&i.Repository,
			&i.RepositoryOwner,
			&i.Workflow,
			&i.Ref,
			&i.Environment,
			&i.RawClaims,
			&i.VerifiedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
