// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Tries to insert the idempotency mapping. If the key already exists, returns
	// the existing report_id. The caller decides whether the row was freshly claimed
	// by comparing report_id against what it just inserted.
	ClaimIdempotencyKey(ctx context.Context, arg ClaimIdempotencyKeyParams) (uuid.UUID, error)
	DeleteOIDCPolicy(ctx context.Context, id uuid.UUID) error
	DeleteReport(ctx context.Context, id uuid.UUID) error
	GetAPIKeyByID(ctx context.Context, id uuid.UUID) (ApiKey, error)
	GetAPIKeyByPrefix(ctx context.Context, keyPrefix string) (ApiKey, error)
	GetArtifactByID(ctx context.Context, id uuid.UUID) (Artifact, error)
	GetIdempotencyMapping(ctx context.Context, idempotencyKey string) (ReportsIdempotency, error)
	GetOIDCPolicyByID(ctx context.Context, id uuid.UUID) (GithubOidcPolicy, error)
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error)
	GetReportByID(ctx context.Context, id uuid.UUID) (Report, error)
	GetReportGroupByID(ctx context.Context, id uuid.UUID) (ReportGroup, error)
	GetReportGroupBySlug(ctx context.Context, slug string) (ReportGroup, error)
	GetReportJSONFileByReport(ctx context.Context, reportID uuid.UUID) (ReportJsonFile, error)
	GetSessionByTokenHash(ctx context.Context, tokenHash string) (Session, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	InsertAPIKey(ctx context.Context, arg InsertAPIKeyParams) (ApiKey, error)
	InsertArtifact(ctx context.Context, arg InsertArtifactParams) (Artifact, error)
	InsertOIDCClaims(ctx context.Context, arg InsertOIDCClaimsParams) (OidcClaim, error)
	InsertOIDCPolicy(ctx context.Context, arg InsertOIDCPolicyParams) (GithubOidcPolicy, error)
	InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) (RefreshToken, error)
	InsertReport(ctx context.Context, arg InsertReportParams) (Report, error)
	InsertReportGroup(ctx context.Context, arg InsertReportGroupParams) (ReportGroup, error)
	InsertReportJSONFile(ctx context.Context, arg InsertReportJSONFileParams) (ReportJsonFile, error)
	InsertSession(ctx context.Context, arg InsertSessionParams) (Session, error)
	InsertSuite(ctx context.Context, arg InsertSuiteParams) (Suite, error)
	InsertTestCase(ctx context.Context, arg InsertTestCaseParams) (TestCase, error)
	ListAPIKeys(ctx context.Context, dollar_1 string) ([]ApiKey, error)
	ListArtifactsByCase(ctx context.Context, testCaseID uuid.UUID) ([]Artifact, error)
	ListEnabledOIDCPolicies(ctx context.Context) ([]GithubOidcPolicy, error)
	ListOIDCClaimsBySubject(ctx context.Context, arg ListOIDCClaimsBySubjectParams) ([]OidcClaim, error)
	ListOIDCPolicies(ctx context.Context) ([]GithubOidcPolicy, error)
	ListReportGroups(ctx context.Context) ([]ReportGroup, error)
	ListReportsByGroup(ctx context.Context, arg ListReportsByGroupParams) ([]Report, error)
	ListSuitesByReport(ctx context.Context, reportID uuid.UUID) ([]Suite, error)
	ListTestCasesByReport(ctx context.Context, arg ListTestCasesByReportParams) ([]TestCase, error)
	ListTestCasesBySuite(ctx context.Context, suiteID uuid.UUID) ([]TestCase, error)
	MarkAPIKeyRotating(ctx context.Context, id uuid.UUID) error
	MarkRefreshTokenUsed(ctx context.Context, arg MarkRefreshTokenUsedParams) error
	MarkReportFailed(ctx context.Context, arg MarkReportFailedParams) error
	MarkReportReady(ctx context.Context, arg MarkReportReadyParams) error
	RevokeAPIKey(ctx context.Context, id uuid.UUID) error
	RevokeSession(ctx context.Context, id uuid.UUID) error
	TouchAPIKeyLastUsed(ctx context.Context, id uuid.UUID) error
	TouchSession(ctx context.Context, id uuid.UUID) error
	UpdateOIDCPolicy(ctx context.Context, arg UpdateOIDCPolicyParams) (GithubOidcPolicy, error)
	UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error
	UpsertUserByGitHubID(ctx context.Context, arg UpsertUserByGitHubIDParams) (User, error)
}

var _ Querier = (*Queries)(nil)
