// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: refresh_tokens.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, session_id, token_hash, issued_at, expires_at, used_at, replaced_by FROM refresh_tokens WHERE token_hash = $1 LIMIT 1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TokenHash,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.ReplacedBy,
	)
	return i, err
}

const insertRefreshToken = `-- name: InsertRefreshToken :one
INSERT INTO refresh_tokens (session_id, token_hash, expires_at)
VALUES ($1, $2, $3)
RETURNING id, session_id, token_hash, issued_at, expires_at, used_at, replaced_by
`

type InsertRefreshTokenParams struct {
	SessionID uuid.UUID `json:"session_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) InsertRefreshToken(ctx context.Context, arg InsertRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, insertRefreshToken, arg.SessionID, arg.TokenHash, arg.ExpiresAt)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.TokenHash,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.ReplacedBy,
	)
	return i, err
}

const markRefreshTokenUsed = `-- name: MarkRefreshTokenUsed :exec
UPDATE refresh_tokens SET used_at = now(), replaced_by = $2 WHERE id = $1
`

type MarkRefreshTokenUsedParams struct {
	ID         uuid.UUID     `json:"id"`
	ReplacedBy uuid.NullUUID `json:"replaced_by"`
}

func (q *Queries) MarkRefreshTokenUsed(ctx context.Context, arg MarkRefreshTokenUsedParams) error {
	_, err := q.db.Exec(ctx, markRefreshTokenUsed, arg.ID, arg.ReplacedBy)
	return err
}
