// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: report_json_files.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const getReportJSONFileByReport = `-- name: GetReportJSONFileByReport :one
SELECT id, report_id, object_key, size_bytes, sha256, created_at FROM report_json_files WHERE report_id = $1 LIMIT 1
`

func (q *Queries) GetReportJSONFileByReport(ctx context.Context, reportID uuid.UUID) (ReportJsonFile, error) {
	row := q.db.QueryRow(ctx, getReportJSONFileByReport, reportID)
	var i ReportJsonFile
	err := row.Scan(
		&i.ID,
		&i.ReportID,
		&i.ObjectKey,
		&i.SizeBytes,
		&i.Sha256,
		&i.CreatedAt,
	)
	return i, err
}

const insertReportJSONFile = `-- name: InsertReportJSONFile :one
INSERT INTO report_json_files (report_id, object_key, size_bytes, sha256)
VALUES ($1, $2, $3, $4)
RETURNING id, report_id, object_key, size_bytes, sha256, created_at
`

type InsertReportJSONFileParams struct {
	ReportID  uuid.UUID `json:"report_id"`
	ObjectKey string    `json:"object_key"`
	SizeBytes int64     `json:"size_bytes"`
	Sha256    string    `json:"sha256"`
}

func (q *Queries) InsertReportJSONFile(ctx context.Context, arg InsertReportJSONFileParams) (ReportJsonFile, error) {
	row := q.db.QueryRow(ctx, insertReportJSONFile,
		arg.ReportID,
		arg.ObjectKey,
		arg.SizeBytes,
		arg.Sha256,
	)
	var i ReportJsonFile
	err := row.Scan(
		&i.ID,
		&i.ReportID,
		&i.ObjectKey,
		&i.SizeBytes,
		&i.Sha256,
		&i.CreatedAt,
	)
	return i, err
}
