// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: report_groups.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const getReportGroupByID = `-- name: GetReportGroupByID :one
SELECT id, slug, display_name, description, created_at FROM report_groups WHERE id = $1 LIMIT 1
`

func (q *Queries) GetReportGroupByID(ctx context.Context, id uuid.UUID) (ReportGroup, error) {
	row := q.db.QueryRow(ctx, getReportGroupByID, id)
	var i ReportGroup
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getReportGroupBySlug = `-- name: GetReportGroupBySlug :one
SELECT id, slug, display_name, description, created_at FROM report_groups WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetReportGroupBySlug(ctx context.Context, slug string) (ReportGroup, error) {
	row := q.db.QueryRow(ctx, getReportGroupBySlug, slug)
	var i ReportGroup
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const insertReportGroup = `-- name: InsertReportGroup :one
INSERT INTO report_groups (slug, display_name, description)
VALUES ($1, $2, $3)
RETURNING id, slug, display_name, description, created_at
`

type InsertReportGroupParams struct {
	Slug        string  `json:"slug"`
	DisplayName string  `json:"display_name"`
	Description *string `json:"description"`
}

func (q *Queries) InsertReportGroup(ctx context.Context, arg InsertReportGroupParams) (ReportGroup, error) {
	row := q.db.QueryRow(ctx, insertReportGroup, arg.Slug, arg.DisplayName, arg.Description)
	var i ReportGroup
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.DisplayName,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const listReportGroups = `-- name: ListReportGroups :many
SELECT id, slug, display_name, description, created_at FROM report_groups ORDER BY created_at DESC
`

func (q *Queries) ListReportGroups(ctx context.Context) ([]ReportGroup, error) {
	rows, err := q.db.Query(ctx, listReportGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportGroup{}
	for rows.Next() {
		var i ReportGroup
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.DisplayName,
			&i.Description,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
