// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const deleteReport = `-- name: DeleteReport :exec
DELETE FROM reports WHERE id = $1
`

func (q *Queries) DeleteReport(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteReport, id)
	return err
}

const getReportByID = `-- name: GetReportByID :one
SELECT id, report_group_id, source, commit_sha, branch, status, ingest_error, total_suites, total_cases, passed_cases, failed_cases, skipped_cases, flaky_cases, duration_ms, uploaded_by_api_key_id, uploaded_by_oidc_subject, idempotency_key, created_at, ingested_at FROM reports WHERE id = $1 LIMIT 1
`

func (q *Queries) GetReportByID(ctx context.Context, id uuid.UUID) (Report, error) {
	row := q.db.QueryRow(ctx, getReportByID, id)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReportGroupID,
		&i.Source,
		&i.CommitSha,
		&i.Branch,
		&i.Status,
		&i.IngestError,
		&i.TotalSuites,
		&i.TotalCases,
		&i.PassedCases,
		&i.FailedCases,
		&i.SkippedCases,
		&i.FlakyCases,
		&i.DurationMs,
		&i.UploadedByApiKeyID,
		&i.UploadedByOidcSubject,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.IngestedAt,
	)
	return i, err
}

const insertReport = `-- name: InsertReport :one
INSERT INTO reports (
    report_group_id, source, commit_sha, branch, status,
    uploaded_by_api_key_id, uploaded_by_oidc_subject, idempotency_key
) VALUES ($1, $2, $3, $4, 'ingesting', $5, $6, $7)
RETURNING id, report_group_id, source, commit_sha, branch, status, ingest_error, total_suites, total_cases, passed_cases, failed_cases, skipped_cases, flaky_cases, duration_ms, uploaded_by_api_key_id, uploaded_by_oidc_subject, idempotency_key, created_at, ingested_at
`

type InsertReportParams struct {
	ReportGroupID         uuid.UUID     `json:"report_group_id"`
	Source                string        `json:"source"`
	CommitSha             *string       `json:"commit_sha"`
	Branch                *string       `json:"branch"`
	UploadedByApiKeyID    uuid.NullUUID `json:"uploaded_by_api_key_id"`
	UploadedByOidcSubject *string       `json:"uploaded_by_oidc_subject"`
	IdempotencyKey        *string       `json:"idempotency_key"`
}

func (q *Queries) InsertReport(ctx context.Context, arg InsertReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, insertReport,
		arg.ReportGroupID,
		arg.Source,
		arg.CommitSha,
		arg.Branch,
		arg.UploadedByApiKeyID,
		arg.UploadedByOidcSubject,
		arg.IdempotencyKey,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReportGroupID,
		&i.Source,
		&i.CommitSha,
		&i.Branch,
		&i.Status,
		&i.IngestError,
		&i.TotalSuites,
		&i.TotalCases,
		&i.PassedCases,
		&i.FailedCases,
		&i.SkippedCases,
		&i.FlakyCases,
		&i.DurationMs,
		&i.UploadedByApiKeyID,
		&i.UploadedByOidcSubject,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.IngestedAt,
	)
	return i, err
}

const listReportsByGroup = `-- name: ListReportsByGroup :many
SELECT id, report_group_id, source, commit_sha, branch, status, ingest_error, total_suites, total_cases, passed_cases, failed_cases, skipped_cases, flaky_cases, duration_ms, uploaded_by_api_key_id, uploaded_by_oidc_subject, idempotency_key, created_at, ingested_at FROM reports
WHERE ($1::uuid IS NULL OR report_group_id = $1)
ORDER BY created_at DESC
LIMIT $2
`

type ListReportsByGroupParams struct {
	Column1 uuid.UUID `json:"column_1"`
	Limit   int32     `json:"limit"`
}

func (q *Queries) ListReportsByGroup(ctx context.Context, arg ListReportsByGroupParams) ([]Report, error) {
	rows, err := q.db.Query(ctx, listReportsByGroup, arg.Column1, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Report{}
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.ReportGroupID,
			&i.Source,
			&i.CommitSha,
			&i.Branch,
			&i.Status,
			&i.IngestError,
			&i.TotalSuites,
			&i.TotalCases,
			&i.PassedCases,
			&i.FailedCases,
			&i.SkippedCases,
			&i.FlakyCases,
			&i.DurationMs,
			&i.UploadedByApiKeyID,
			&i.UploadedByOidcSubject,
			&i.IdempotencyKey,
			&i.CreatedAt,
			&i.IngestedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markReportFailed = `-- name: MarkReportFailed :exec
UPDATE reports SET status = 'failed', ingest_error = $2 WHERE id = $1
`

type MarkReportFailedParams struct {
	ID          uuid.UUID `json:"id"`
	IngestError *string   `json:"ingest_error"`
}

func (q *Queries) MarkReportFailed(ctx context.Context, arg MarkReportFailedParams) error {
	_, err := q.db.Exec(ctx, markReportFailed, arg.ID, arg.IngestError)
	return err
}

const markReportReady = `-- name: MarkReportReady :exec
UPDATE reports
SET status = 'ready',
    total_suites = $2,
    total_cases = $3,
    passed_cases = $4,
    failed_cases = $5,
    skipped_cases = $6,
    flaky_cases = $7,
    duration_ms = $8,
    ingested_at = now()
WHERE id = $1
`

type MarkReportReadyParams struct {
	ID           uuid.UUID `json:"id"`
	TotalSuites  int32     `json:"total_suites"`
	TotalCases   int32     `json:"total_cases"`
	PassedCases  int32     `json:"passed_cases"`
	FailedCases  int32     `json:"failed_cases"`
	SkippedCases int32     `json:"skipped_cases"`
	FlakyCases   int32     `json:"flaky_cases"`
	DurationMs   *int64    `json:"duration_ms"`
}

func (q *Queries) MarkReportReady(ctx context.Context, arg MarkReportReadyParams) error {
	_, err := q.db.Exec(ctx, markReportReady,
		arg.ID,
		arg.TotalSuites,
		arg.TotalCases,
		arg.PassedCases,
		arg.FailedCases,
		arg.SkippedCases,
		arg.FlakyCases,
		arg.DurationMs,
	)
	return err
}
