// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports_idempotency.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const claimIdempotencyKey = `-- name: ClaimIdempotencyKey :one
INSERT INTO reports_idempotency (idempotency_key, report_id)
VALUES ($1, $2)
ON CONFLICT (idempotency_key) DO UPDATE SET report_id = reports_idempotency.report_id
RETURNING report_id
`

type ClaimIdempotencyKeyParams struct {
	IdempotencyKey string    `json:"idempotency_key"`
	ReportID       uuid.UUID `json:"report_id"`
}

// Tries to insert the idempotency mapping. If the key already exists, returns
// the existing report_id. The caller decides whether the row was freshly claimed
// by comparing report_id against what it just inserted.
func (q *Queries) ClaimIdempotencyKey(ctx context.Context, arg ClaimIdempotencyKeyParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, claimIdempotencyKey, arg.IdempotencyKey, arg.ReportID)
	var report_id uuid.UUID
	err := row.Scan(&report_id)
	return report_id, err
}

const getIdempotencyMapping = `-- name: GetIdempotencyMapping :one
SELECT idempotency_key, report_id, claimed_at FROM reports_idempotency WHERE idempotency_key = $1 LIMIT 1
`

func (q *Queries) GetIdempotencyMapping(ctx context.Context, idempotencyKey string) (ReportsIdempotency, error) {
	row := q.db.QueryRow(ctx, getIdempotencyMapping, idempotencyKey)
	var i ReportsIdempotency
	err := row.Scan(&i.IdempotencyKey, &i.ReportID, &i.ClaimedAt)
	return i, err
}
