// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sessions.sql

package sqlcgen

import (
	"context"
	"net/netip"
	"time"

	"github.com/google/uuid"
)

const getSessionByTokenHash = `-- name: GetSessionByTokenHash :one
SELECT id, token_hash, user_id, issued_at, expires_at, last_seen_at, ip, user_agent, revoked_at FROM sessions WHERE token_hash = $1 AND revoked_at IS NULL AND expires_at > now() LIMIT 1
`

func (q *Queries) GetSessionByTokenHash(ctx context.Context, tokenHash string) (Session, error) {
	row := q.db.QueryRow(ctx, getSessionByTokenHash, tokenHash)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.UserID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.Ip,
		&i.UserAgent,
		&i.RevokedAt,
	)
	return i, err
}

const insertSession = `-- name: InsertSession :one
INSERT INTO sessions (token_hash, user_id, expires_at, ip, user_agent)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, token_hash, user_id, issued_at, expires_at, last_seen_at, ip, user_agent, revoked_at
`

type InsertSessionParams struct {
	TokenHash string      `json:"token_hash"`
	UserID    uuid.UUID   `json:"user_id"`
	ExpiresAt time.Time   `json:"expires_at"`
	Ip        *netip.Addr `json:"ip"`
	UserAgent *string     `json:"user_agent"`
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) (Session, error) {
	row := q.db.QueryRow(ctx, insertSession,
		arg.TokenHash,
		arg.UserID,
		arg.ExpiresAt,
		arg.Ip,
		arg.UserAgent,
	)
	var i Session
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.UserID,
		&i.IssuedAt,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.Ip,
		&i.UserAgent,
		&i.RevokedAt,
	)
	return i, err
}

const revokeSession = `-- name: RevokeSession :exec
UPDATE sessions SET revoked_at = now() WHERE id = $1
`

func (q *Queries) RevokeSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeSession, id)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE sessions SET last_seen_at = now() WHERE id = $1
`

func (q *Queries) TouchSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, touchSession, id)
	return err
}
