// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: suites.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const insertSuite = `-- name: InsertSuite :one
INSERT INTO suites (report_id, parent_suite_id, title, file, line, col, duration_ms, ordinal)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, report_id, parent_suite_id, title, file, line, col, duration_ms, ordinal
`

type InsertSuiteParams struct {
	ReportID      uuid.UUID     `json:"report_id"`
	ParentSuiteID uuid.NullUUID `json:"parent_suite_id"`
	Title         string        `json:"title"`
	File          string        `json:"file"`
	Line          *int32        `json:"line"`
	Col           *int32        `json:"col"`
	DurationMs    *int64        `json:"duration_ms"`
	Ordinal       int32         `json:"ordinal"`
}

func (q *Queries) InsertSuite(ctx context.Context, arg InsertSuiteParams) (Suite, error) {
	row := q.db.QueryRow(ctx, insertSuite,
		arg.ReportID,
		arg.ParentSuiteID,
		arg.Title,
		arg.File,
		arg.Line,
		arg.Col,
		arg.DurationMs,
		arg.Ordinal,
	)
	var i Suite
	err := row.Scan(
		&i.ID,
		&i.ReportID,
		&i.ParentSuiteID,
		&i.Title,
		&i.File,
		&i.Line,
		&i.Col,
		&i.DurationMs,
		&i.Ordinal,
	)
	return i, err
}

const listSuitesByReport = `-- name: ListSuitesByReport :many
SELECT id, report_id, parent_suite_id, title, file, line, col, duration_ms, ordinal FROM suites WHERE report_id = $1 ORDER BY parent_suite_id NULLS FIRST, ordinal
`

func (q *Queries) ListSuitesByReport(ctx context.Context, reportID uuid.UUID) ([]Suite, error) {
	rows, err := q.db.Query(ctx, listSuitesByReport, reportID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Suite{}
	for rows.Next() {
		var i Suite
		if err := rows.Scan(
			&i.ID,
			&i.ReportID,
			&i.ParentSuiteID,
			&i.Title,
			&i.File,
			&i.Line,
			&i.Col,
			&i.DurationMs,
			&i.Ordinal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
