// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: test_cases.sql

package sqlcgen

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const insertTestCase = `-- name: InsertTestCase :one
INSERT INTO test_cases (
    suite_id, title, status, retry_count, duration_ms,
    error_message, error_stack, annotations, ordinal
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, suite_id, title, status, retry_count, duration_ms, error_message, error_stack, annotations, ordinal
`

type InsertTestCaseParams struct {
	SuiteID      uuid.UUID       `json:"suite_id"`
	Title        string          `json:"title"`
	Status       string          `json:"status"`
	RetryCount   int32           `json:"retry_count"`
	DurationMs   *int64          `json:"duration_ms"`
	ErrorMessage *string         `json:"error_message"`
	ErrorStack   *string         `json:"error_stack"`
	Annotations  json.RawMessage `json:"annotations"`
	Ordinal      int32           `json:"ordinal"`
}

func (q *Queries) InsertTestCase(ctx context.Context, arg InsertTestCaseParams) (TestCase, error) {
	row := q.db.QueryRow(ctx, insertTestCase,
		arg.SuiteID,
		arg.Title,
		arg.Status,
		arg.RetryCount,
		arg.DurationMs,
		arg.ErrorMessage,
		arg.ErrorStack,
		arg.Annotations,
		arg.Ordinal,
	)
	var i TestCase
	err := row.Scan(
		&i.ID,
		&i.SuiteID,
		&i.Title,
		&i.Status,
		&i.RetryCount,
		&i.DurationMs,
		&i.ErrorMessage,
		&i.ErrorStack,
		&i.Annotations,
		&i.Ordinal,
	)
	return i, err
}

const listTestCasesByReport = `-- name: ListTestCasesByReport :many
SELECT tc.id, tc.suite_id, tc.title, tc.status, tc.retry_count, tc.duration_ms, tc.error_message, tc.error_stack, tc.annotations, tc.ordinal
FROM test_cases tc
JOIN suites s ON s.id = tc.suite_id
WHERE s.report_id = $1
  AND ($2::text IS NULL OR tc.status = $2)
ORDER BY s.ordinal, tc.ordinal
`

type ListTestCasesByReportParams struct {
	ReportID uuid.UUID `json:"report_id"`
	Column2  string    `json:"column_2"`
}

func (q *Queries) ListTestCasesByReport(ctx context.Context, arg ListTestCasesByReportParams) ([]TestCase, error) {
	rows, err := q.db.Query(ctx, listTestCasesByReport, arg.ReportID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TestCase{}
	for rows.Next() {
		var i TestCase
		if err := rows.Scan(
			&i.ID,
			&i.SuiteID,
			&i.Title,
			&i.Status,
			&i.RetryCount,
			&i.DurationMs,
			&i.ErrorMessage,
			&i.ErrorStack,
			&i.Annotations,
			&i.Ordinal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTestCasesBySuite = `-- name: ListTestCasesBySuite :many
SELECT id, suite_id, title, status, retry_count, duration_ms, error_message, error_stack, annotations, ordinal FROM test_cases WHERE suite_id = $1 ORDER BY ordinal
`

func (q *Queries) ListTestCasesBySuite(ctx context.Context, suiteID uuid.UUID) ([]TestCase, error) {
	rows, err := q.db.Query(ctx, listTestCasesBySuite, suiteID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TestCase{}
	for rows.Next() {
		var i TestCase
		if err := rows.Scan(
			&i.ID,
			&i.SuiteID,
			&i.Title,
			&i.Status,
			&i.RetryCount,
			&i.DurationMs,
			&i.ErrorMessage,
			&i.ErrorStack,
			&i.Annotations,
			&i.Ordinal,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
