// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const getUserByID = `-- name: GetUserByID :one
SELECT id, github_id, github_login, email, display_name, avatar_url, role, created_at, last_login_at FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.GithubLogin,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Role,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :exec
UPDATE users SET role = $2 WHERE id = $1
`

type UpdateUserRoleParams struct {
	ID   uuid.UUID `json:"id"`
	Role string    `json:"role"`
}

func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) error {
	_, err := q.db.Exec(ctx, updateUserRole, arg.ID, arg.Role)
	return err
}

const upsertUserByGitHubID = `-- name: UpsertUserByGitHubID :one
INSERT INTO users (github_id, github_login, email, display_name, avatar_url)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (github_id) DO UPDATE
    SET github_login = EXCLUDED.github_login,
        email = EXCLUDED.email,
        display_name = EXCLUDED.display_name,
        avatar_url = EXCLUDED.avatar_url,
        last_login_at = now()
RETURNING id, github_id, github_login, email, display_name, avatar_url, role, created_at, last_login_at
`

type UpsertUserByGitHubIDParams struct {
	GithubID    int64   `json:"github_id"`
	GithubLogin string  `json:"github_login"`
	Email       *string `json:"email"`
	DisplayName *string `json:"display_name"`
	AvatarUrl   *string `json:"avatar_url"`
}

func (q *Queries) UpsertUserByGitHubID(ctx context.Context, arg UpsertUserByGitHubIDParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUserByGitHubID,
		arg.GithubID,
		arg.GithubLogin,
		arg.Email,
		arg.DisplayName,
		arg.AvatarUrl,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.GithubID,
		&i.GithubLogin,
		&i.Email,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Role,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}
